In [2]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv('cars.csv')
df.sample(10)

           brand  km_driven    fuel         owner  selling_price
7944    Mahindra     100000  Petrol  Second Owner         350000
5993     Hyundai      80000  Petrol   Third Owner          85000
2839        Ford      62000  Diesel   First Owner         700000
6368      Maruti      20000  Petrol   First Owner         580000
7292  Volkswagen      69000  Diesel   First Owner         651000
3587        Ford       2860  Diesel   First Owner         795000
2562    Mahindra     110000  Petrol   First Owner         426000
3732      Maruti      90000  Diesel  Second Owner         375000
7498      Toyota     200000  Diesel   Third Owner         500000
4964     Renault       5000  Petrol   First Owner         600000

In [6]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

# **1.OneHotEncoding using pandas**

In [7]:
pd.get_dummies(df,columns=['fuel','owner'],dtype=int)

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,0,1,0,0,1,0,0,0,0
1,Skoda,120000,370000,0,1,0,0,0,0,1,0,0
2,Honda,140000,158000,0,0,0,1,0,0,0,0,1
3,Hyundai,127000,225000,0,1,0,0,1,0,0,0,0
4,Maruti,120000,130000,0,0,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,0,1,1,0,0,0,0
8124,Hyundai,119000,135000,0,1,0,0,0,1,0,0,0
8125,Maruti,120000,382000,0,1,0,0,1,0,0,0,0
8126,Tata,25000,290000,0,1,0,0,1,0,0,0,0
8127,Tata,25000,290000,0,1,0,0,1,0,0,0,0

# **2.K-1 OneHotEncoding**
**Handling dummy trap**

In [8]:
pd.get_dummies(df,columns=['fuel','owner'],dtype=int,drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,1,0,0,0,0,0,0
1,Skoda,120000,370000,1,0,0,0,1,0,0
2,Honda,140000,158000,0,0,1,0,0,0,1
3,Hyundai,127000,225000,1,0,0,0,0,0,0
4,Maruti,120000,130000,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,1,0,0,0,0
8124,Hyundai,119000,135000,1,0,0,1,0,0,0
8125,Maruti,120000,382000,1,0,0,0,0,0,0
8126,Tata,25000,290000,1,0,0,0,0,0,0
8127,Tata,25000,290000,1,0,0,0,0,0,0

# **3. OneHotEncoding using Sklearn**

**See we can do one-hot encoding using pandas which we did above but the problem is pandas forget which column he has drop in dummy trap. So alwas you will get new drop column.To solve this we will use skit learn libray to use Onehotencoder() which remember everything**

In [54]:
df.sample()

     brand  km_driven    fuel        owner  selling_price
3202  Ford      80000  Diesel  First Owner         300000

In [42]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=2)

In [43]:
X_train.head()

         brand  km_driven    fuel         owner
5571   Hyundai      35000  Diesel   First Owner
2038      Jeep      60000  Diesel   First Owner
2957   Hyundai      25000  Petrol   First Owner
7618  Mahindra     130000  Diesel  Second Owner
6684   Hyundai     155000  Diesel   First Owner

In [44]:
from sklearn.preprocessing import OneHotEncoder

In [45]:
ohe = OneHotEncoder(drop='first',dtype=np.int32,sparse_output=False)

In [46]:
X_train_new = ohe.fit_transform(X_train[['fuel','owner']])

In [47]:
X_test_new = ohe.transform(X_test[['fuel','owner']])

In [48]:
X_train_new.shape

(6502, 7)

In [49]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new))

array([['Hyundai', 35000, 1, ..., 0, 0, 0],
       ['Jeep', 60000, 1, ..., 0, 0, 0],
       ['Hyundai', 25000, 0, ..., 0, 0, 0],
       ...,
       ['Tata', 15000, 0, ..., 0, 0, 0],
       ['Maruti', 32500, 1, ..., 1, 0, 0],
       ['Isuzu', 121000, 1, ..., 0, 0, 0]], shape=(6502, 9), dtype=object)

# **4. OneHotEncoding with Top Categories**

In [50]:
counts = df['brand'].value_counts()

In [51]:
df['brand'].nunique()
threshold = 100

In [52]:
repl = counts[counts <= threshold].index

In [53]:
pd.get_dummies(df['brand'].replace(repl, 'uncommon'),dtype=np.int32).sample(15)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
4683,0,0,0,0,0,1,0,0,0,0,0,0,0
5146,0,0,0,0,0,0,1,0,0,0,0,0,0
5708,0,0,0,0,0,0,1,0,0,0,0,0,0
1189,0,0,0,0,0,1,0,0,0,0,0,0,0
7733,0,0,0,0,0,0,1,0,0,0,0,0,0
1689,0,0,0,0,0,1,0,0,0,0,0,0,0
3326,0,0,0,0,0,0,0,0,0,0,1,0,0
1859,0,0,0,0,0,0,0,0,0,0,0,0,1
3548,0,0,0,0,0,0,0,0,0,0,1,0,0
481,0,0,0,0,0,0,1,0,0,0,0,0,0
4851,0,0,0,0,0,0,0,0,0,0,1,0,0
3917,0,0,0,0,0,0,0,0,0,1,0,0,0
1634,0,0,0,0,1,0,0,0,0,0,0,0,0
7910,0,0,0,0,0,0,1,0,0,0,0,0,0
6789,0,0,0,0,0,0,1,0,0,0,0,0,0