In [11]:
import numpy as np
import pandas as pd

In [12]:
df = pd.read_csv('covid_toy.csv')
df.sample(5)

    age  gender  fever   cough       city has_covid
46   19  Female  101.0    Mild     Mumbai        No
30   15    Male  101.0    Mild      Delhi       Yes
78   11    Male  100.0    Mild  Bangalore       Yes
23   80  Female   98.0    Mild      Delhi       Yes
32   34  Female  101.0  Strong      Delhi       Yes

In [13]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [14]:
df.sample()

    age gender  fever cough       city has_covid
63   10   Male  100.0  Mild  Bangalore        No

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [16]:
X_train

    age  gender  fever   cough       city
76   80    Male  100.0    Mild  Bangalore
39   50  Female  103.0    Mild    Kolkata
49   44    Male  104.0    Mild     Mumbai
21   73    Male   98.0    Mild  Bangalore
83   17  Female  104.0    Mild    Kolkata
..  ...     ...    ...     ...        ...
40   49  Female  102.0    Mild      Delhi
1    27    Male  100.0    Mild      Delhi
18   64  Female   98.0    Mild  Bangalore
35   82  Female  102.0  Strong  Bangalore
44   20    Male  102.0  Strong      Delhi

[80 rows x 5 columns]

# **Performing column Transformation by 2 method**

**1.Aam Zindagi**

In [18]:
# adding simple imputer to fever col
from sklearn.impute import SimpleImputer
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data
X_test_fever = si.fit_transform(X_test[['fever']])
                                 
X_train_fever.shape

(80, 1)

In [26]:
# Ordinalencoding -> cough
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

# also the test data
X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough.shape

(80, 1)

In [31]:
# OneHotEncoding -> gender,city
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop='first',sparse_output=False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

# also the test data
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city.shape

(80, 4)

In [32]:
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape

(80, 1)

In [33]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
# also the test data
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

X_train_transformed.shape

(80, 7)

# **Mentos Zindagi**

In [39]:
from sklearn.compose import ColumnTransformer

In [45]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer,['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [46]:
transformer.fit_transform(X_train).shape

TypeError: Cannot clone object. You should provide an instance of scikit-learn estimator instead of a class.