# **Fetching data from URL**

In [8]:
import pandas as pd
import requests

In [9]:
response = requests.get('https://newsdata.io/api/1/latest?apikey=pub_4a383d9f98e0486a91ddfcd6d658b86a')

**Now converting into Dataframe**

In [10]:
# we have api by hitting it we are getting in json format so first we have to bring to json and then dataframe
df = pd.DataFrame(response.json()['results'])[['article_id','title','description','content','creator','language','country']]
df

,article_id,title,description,content,creator,language,country
0,f20569ed5c864d64be665c09eb8cb423,Big Ten commissioner pushes back on talk of br...,CHICAGO — After leaders of the Southeastern Co...,ONLY AVAILABLE IN PAID PLANS,None,english,[united states of america]
1,4337535267b6cfeed984f53d3c85ad76,Samenvatting: ExaGrid brengt versie 8.1 uit,"MARLBOROUGH, Mass.--(BUSINESS WIRE)--ExaGrid®,...",ONLY AVAILABLE IN PAID PLANS,None,dutch,"[canada, france, germany, united kingdom, chin..."
2,59b92a19c8387c55551b543dd70296f7,Explosión en un edificio de Monteagudo al 100...,La principal hipótesis apunta a una pérdida ...,ONLY AVAILABLE IN PAID PLANS,[belén castellano],spanish,[argentina]
3,0cb1bef5613d27eb04cee000c921c7f8,Big Ten commissioner pushes back on talk of br...,CHICAGO — After leaders of the Southeastern Co...,ONLY AVAILABLE IN PAID PLANS,None,english,[united states of america]
4,c099841233a20d1a605bc6de40d9574b,VIDEO ⟩ Pie sociālās aprūpes centra Jelgava...,Jelgavā pie Valsts sociālās aprūpes centra...,ONLY AVAILABLE IN PAID PLANS,None,latvian,[latvia]
5,d6385eff780ff69c58fee08f593018df,Lula cita o SUS e provoca Trump em visita de d...,O presidente Luiz Inácio Lula da Silva pediu ...,ONLY AVAILABLE IN PAID PLANS,None,portuguese,[brazil]
6,ae01ac18792afdac9e843c93033a24fd,Keiko Fujimori innsatt som Perus president,Keiko Fujimori lover hard kamp mot kriminalite...,ONLY AVAILABLE IN PAID PLANS,[ntb-afp null],norwegian,[norway]
7,357deb566ec0c0f10cb7faf0265da6c6,La FIFA mette in 'vendita' la Coppa del Mondo?...,None,ONLY AVAILABLE IN PAID PLANS,[luca bargellini],italian,[italy]
8,ba6009bddbcf6bc9585117f994cbf988,Big Ten commissioner pushes back on talk of br...,CHICAGO — After leaders of the Southeastern Co...,ONLY AVAILABLE IN PAID PLANS,[ryan kartje; los angeles times],english,[united states of america]
9,8fd76bdbeb08ddf0416d981fd3cb33e1,Big Ten commissioner pushes back on talk of br...,CHICAGO — After leaders of the Southeastern Co...,ONLY AVAILABLE IN PAID PLANS,None,english,[united states of america]

In [18]:
import pandas as pd
import requests

df = pd.DataFrame()

for i in range(1, 11):
    response = requests.get("https://newsdata.io/api/1/latest?apikey=pub_4a383d9f98e0486a91ddfcd6d658b86a")
    
    temp_df = pd.DataFrame(response.json()['results'])[
        ['article_id', 'title', 'description', 'content', 'creator', 'language', 'country']
    ]
    
    df = pd.concat([df, temp_df], ignore_index=True)

In [19]:
df

,article_id,title,description,content,creator,language,country
0,4c6877d115a60359ed8cc178c44520a9,63 POKFULAM開放戶呎租91元 近1年新高,"【明報專訊】暑假住宅租務旺季下,港島、屯門區私宅繼續錄得內地生租賃成交;當中薄扶林道63 P...",ONLY AVAILABLE IN PAID PLANS,None,chinese,[hong kong]
1,41c0317f9435e36af6b9fd319450d563,Morte de bebê em creche de São Paulo leva à...,A Polícia Civil de São Paulo investiga a mor...,ONLY AVAILABLE IN PAID PLANS,[monise souza],portuguese,[brazil]
2,da093e145ed6856c42d1eee388edaa23,浪翠園3房660萬沽 較97年價低一成 御龍山兩房948萬易手 呎價逾1.91萬見同類戶5年新高,"【明報專訊】雖然近期二手市場有不少短炒獲利個案,惟同時不乏蝕讓成交;被形容為「97重災區」屋...",ONLY AVAILABLE IN PAID PLANS,None,chinese,[hong kong]
3,1b4a83f97006b9e975f08179d24e1052,5 states offer to accept nuclear waste in exch...,5 states offer to accept nuclear waste in exch...,ONLY AVAILABLE IN PAID PLANS,None,english,[united states of america]
4,d59b60294c9a22a38fac04ce16f333b8,湯文亮:香港有夜景 無夜生活,"【明報專訊】星期二早上去到茶餐廳,有客人話昨晚同內地朋友一家人食飯,之後坐遊艇在維港兩岸睇夜...",ONLY AVAILABLE IN PAID PLANS,[湯文亮 茶餐廳手記],chinese,[hong kong]
...,...,...,...,...,...,...,...
95,796f87811e5d3aa81f9127698e48ffda,Youths held at Kearney center accuse staff of ...,The Office of the Inspector General's report c...,ONLY AVAILABLE IN PAID PLANS,None,english,[united states of america]
96,0acc3a73478eca549e9e39e34ab823ba,周顯:日本再加息 日銀隨時爆煲,"【明報專訊】昨天講到日圓匯價四連跌,因此不停加息,但加幅仍然比不上國際大勢。如果日本再加息下...",ONLY AVAILABLE IN PAID PLANS,[周顯 投資二三事],chinese,[hong kong]
97,bec30495254b4e5921c5b7a1658f4d5f,Ilia Malinin teases return to figure skating c...,"The ""Quad God"" has indicated he will soon be b...",ONLY AVAILABLE IN PAID PLANS,[jordan mendoza usa today; jordan mendoza],english,[united states of america]
98,5fadc10df2ebdd507b412e78f199ca80,Ilia Malinin teases return to figure skating c...,"The ""Quad God"" has indicated he will soon be b...",ONLY AVAILABLE IN PAID PLANS,None,english,[united states of america]
99,2924edf9658e2367e26568ceb3376cd9,نبض مسکن در مناطق 15 تا 21,دنیای‌ اقتصاد: جدول امروز نبض بازار را فایل‌ها...,ONLY AVAILABLE IN PAID PLANS,[روزنامه دنیای اقتصاد],persian,[iran]

In [20]:
df.to_csv('Language')